#!/usr/bin/env bash

_BUILD_QA_SITE_SUBSCRIPTION_ENVIRONMENT=test
_BUILD_QA_SITE_WORKSPACE="${HOME}/open_solutions"
_BUILD_QA_SITE_DB_SRC="local"
_BUILD_QA_SITE_DB_DST="qa"
_BUILD_QA_SITE_APACHE_PATH="/var/www/html"
_BUILD_QA_SITE_DOCKER_CONTAINER="os_cli"
