#!/usr/bin/env bash

_CTECH_DEPLOY_WORKSPACE="${HOME}/open_solutions"
_CTECH_DEPLOY_FORK_WORKSPACE="${_CTECH_DEPLOY_WORKSPACE}/forks"
_CTECH_DEPLOY_ACQUIA_WORKSPACE="${_CTECH_DEPLOY_WORKSPACE}/acquia"
_CTECH_DEPLOY_TEMP_PATCH_FOLDER="/tmp/ctech-deploy-patches"
_CTECH_DEPLOY_DOCKER_CONTAINER="os_cli"
